### ISSUE TITLE
module not initialized

### ISSUE THREAD

**Issue by excennfahnfah1976** [shiftpi/CountryFlags#2]
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ShiftpiCountryFlags) could not be initialized.' in C:\www\wamp\www\zf2-tutorial\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php on line 175

**Comment by shiftpi** [comment]
Could you please provide some additional information.
How have you installed the module (Composer) and which version? Which version of ZF are you using, which of PHP?
In my environment it is working fine (Windows and Linux).

**Comment by excennfahnfah1976** [comment]
Ik work, i have installed it with composer now it work very good

**Comment by shiftpi** [comment]
Ok, nice to hear, happy coding
