### ISSUE TITLE
$this->countryFlagUrl('BR', 64)

### ISSUE THREAD

**Issue by excennfahnfah1976** [shiftpi/CountryFlags#3]
when i use the View Helper $this->countryFlagUrl('BR', 64); to show the flag i get this string: /en-US/countryflags/BR/64.
I m using PHP 5.5.9-1ubuntu4.2 
and zf 2.3.1
Thank you

**Comment by shiftpi** [comment]
Where is the problem?
The view helper works as expected. It will give you only an URL back. The `/en-US` part can not be generated by the module. It must be something of your app.

Example usage:
`<img src="<?php echo $this->countryFlagUrl('BR', 64) ?>" alt="Brazil" width="64" />`

**Comment by excennfahnfah1976** [comment]
Sorry it work as expected, i have done wrong things

**Comment by shiftpi** [comment]
Ok, nice to hear, happy coding
